name: Pytest & lint check

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: src

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-

      - name: Install dependencies
        run: uv sync

      - name: Run lint
        run: uv run ruff check .

      - name: Run tests
        run: DATABASE_URL=sqlite:///test.db PYTHONPATH=src uv run pytest -s --cov=app --cov-report=term-missing
